/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    AiResponse,
    ApiError,
    ConvertResponse,
    CorrelationResponse,
    CountriesResponseInner,
    CurrenciesResponseInner,
    DrawdownResponse,
    HistoryAnalysisResponse,
    HistoryResponse,
    MeanReversionResponse,
    PppAnalysisResponse,
    RatesByBaseResponse,
    RatesResponse,
    SafeHavenResponse,
    VolatilityResponse,
} from '../models/index';

export interface AiRequest {
    q: string;
}

export interface ConvertRequest {
    from: string;
    to: string;
    amount?: number;
    ppp?: boolean;
    date?: string;
}

export interface CorrelationRequest {
    currencies: string;
    base?: string;
    from?: string;
    to?: string;
}

export interface DrawdownRequest {
    currency?: string;
    base?: string;
    from?: string;
    to?: string;
    sort?: string;
    universe?: string;
    limit?: number;
}

export interface HistoryRequest {
    currency: string;
    from?: string;
    to?: string;
    base?: string;
    interval?: string;
}

export interface HistoryAnalysisRequest {
    base?: string;
    currencies?: string;
    from?: string;
    to?: string;
    period?: string;
    sort?: string;
    assetClass?: string;
    limit?: number;
    interval?: string;
    stats?: boolean;
}

export interface MeanReversionRequest {
    currencies?: string;
    base?: string;
    from?: string;
    to?: string;
    limit?: number;
}

export interface PppAnalysisRequest {
    countries?: string;
    from?: string;
    to?: string;
    period?: string;
    sort?: string;
    limit?: number;
    stats?: boolean;
}

export interface RatesRequest {
    date?: string;
}

export interface RatesByBaseRequest {
    base: string;
    date?: string;
}

export interface SafeHavenRequest {
    currencies?: string;
    base?: string;
    from?: string;
    to?: string;
    limit?: number;
}

export interface VolatilityRequest {
    currency?: string;
    base?: string;
    from?: string;
    to?: string;
    sort?: string;
    universe?: string;
    limit?: number;
}

/**
 * 
 */
export class CurrencyCoreApi extends runtime.BaseAPI {

    /**
     * Creates request options for ai without sending the request
     */
    async aiRequestOpts(requestParameters: AiRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling ai().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ai`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ask a natural-language currency question; the model answers using live rates.
     * AI
     */
    async aiRaw(requestParameters: AiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiResponse>> {
        const requestOptions = await this.aiRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Ask a natural-language currency question; the model answers using live rates.
     * AI
     */
    async ai(requestParameters: AiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiResponse> {
        const response = await this.aiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for convert without sending the request
     */
    async convertRequestOpts(requestParameters: ConvertRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['from'] == null) {
            throw new runtime.RequiredError(
                'from',
                'Required parameter "from" was null or undefined when calling convert().'
            );
        }

        if (requestParameters['to'] == null) {
            throw new runtime.RequiredError(
                'to',
                'Required parameter "to" was null or undefined when calling convert().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        if (requestParameters['ppp'] != null) {
            queryParameters['ppp'] = requestParameters['ppp'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/convert`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Convert an amount between currencies, optionally PPP-adjusted.
     * Convert
     */
    async convertRaw(requestParameters: ConvertRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConvertResponse>> {
        const requestOptions = await this.convertRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Convert an amount between currencies, optionally PPP-adjusted.
     * Convert
     */
    async convert(requestParameters: ConvertRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConvertResponse> {
        const response = await this.convertRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for correlation without sending the request
     */
    async correlationRequestOpts(requestParameters: CorrelationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currencies'] == null) {
            throw new runtime.RequiredError(
                'currencies',
                'Required parameter "currencies" was null or undefined when calling correlation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/correlation`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Correlation of each currency\'s daily returns with a base currency\'s, over a window. Growth plan or higher.
     * Correlation
     */
    async correlationRaw(requestParameters: CorrelationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorrelationResponse>> {
        const requestOptions = await this.correlationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Correlation of each currency\'s daily returns with a base currency\'s, over a window. Growth plan or higher.
     * Correlation
     */
    async correlation(requestParameters: CorrelationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorrelationResponse> {
        const response = await this.correlationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for countries without sending the request
     */
    async countriesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/countries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The supported countries and their official currencies. Public, no key needed.
     * Countries
     */
    async countriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CountriesResponseInner>>> {
        const requestOptions = await this.countriesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * The supported countries and their official currencies. Public, no key needed.
     * Countries
     */
    async countries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CountriesResponseInner>> {
        const response = await this.countriesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for currencies without sending the request
     */
    async currenciesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/currencies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The full list of supported ISO 4217 currencies. Use it to resolve a name or symbol to its code, or to check whether a currency is supported (so a missing one fails clearly, not silently). Public, no key needed.
     * Currencies
     */
    async currenciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurrenciesResponseInner>>> {
        const requestOptions = await this.currenciesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * The full list of supported ISO 4217 currencies. Use it to resolve a name or symbol to its code, or to check whether a currency is supported (so a missing one fails clearly, not silently). Public, no key needed.
     * Currencies
     */
    async currencies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurrenciesResponseInner>> {
        const response = await this.currenciesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for drawdown without sending the request
     */
    async drawdownRequestOpts(requestParameters: DrawdownRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['universe'] != null) {
            queryParameters['universe'] = requestParameters['universe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/drawdown`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Maximum peak-to-trough decline vs a base (with peak/trough/recovery), or a drawdown ranking. Growth plan or higher.
     * Drawdown
     */
    async drawdownRaw(requestParameters: DrawdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DrawdownResponse>> {
        const requestOptions = await this.drawdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Maximum peak-to-trough decline vs a base (with peak/trough/recovery), or a drawdown ranking. Growth plan or higher.
     * Drawdown
     */
    async drawdown(requestParameters: DrawdownRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DrawdownResponse> {
        const response = await this.drawdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for history without sending the request
     */
    async historyRequestOpts(requestParameters: HistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling history().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * A single currency\'s daily rate time series over a date range. Growth plan or higher.
     * History
     */
    async historyRaw(requestParameters: HistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HistoryResponse>> {
        const requestOptions = await this.historyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * A single currency\'s daily rate time series over a date range. Growth plan or higher.
     * History
     */
    async history(requestParameters: HistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HistoryResponse> {
        const response = await this.historyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for historyAnalysis without sending the request
     */
    async historyAnalysisRequestOpts(requestParameters: HistoryAnalysisRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['assetClass'] != null) {
            queryParameters['assetClass'] = requestParameters['assetClass'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['stats'] != null) {
            queryParameters['stats'] = requestParameters['stats'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/history/analysis`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Trends, comparisons & \'movers\': % change, strength, and min/max/avg over a window. Growth plan or higher.
     * History analysis
     */
    async historyAnalysisRaw(requestParameters: HistoryAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HistoryAnalysisResponse>> {
        const requestOptions = await this.historyAnalysisRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Trends, comparisons & \'movers\': % change, strength, and min/max/avg over a window. Growth plan or higher.
     * History analysis
     */
    async historyAnalysis(requestParameters: HistoryAnalysisRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HistoryAnalysisResponse> {
        const response = await this.historyAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for meanReversion without sending the request
     */
    async meanReversionRequestOpts(requestParameters: MeanReversionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies'];
        }

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/mean-reversion`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ranks currencies by how strongly they revert to their mean (crossing frequency + reversion half-life). Growth plan or higher.
     * Mean reversion
     */
    async meanReversionRaw(requestParameters: MeanReversionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeanReversionResponse>> {
        const requestOptions = await this.meanReversionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Ranks currencies by how strongly they revert to their mean (crossing frequency + reversion half-life). Growth plan or higher.
     * Mean reversion
     */
    async meanReversion(requestParameters: MeanReversionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeanReversionResponse> {
        const response = await this.meanReversionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pppAnalysis without sending the request
     */
    async pppAnalysisRequestOpts(requestParameters: PppAnalysisRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['countries'] != null) {
            queryParameters['countries'] = requestParameters['countries'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['stats'] != null) {
            queryParameters['stats'] = requestParameters['stats'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ppp/analysis`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * PPP over time: how a country\'s purchasing-power-parity factor changed, comparing countries, or \'movers\'. Growth plan or higher.
     * PPP analysis
     */
    async pppAnalysisRaw(requestParameters: PppAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PppAnalysisResponse>> {
        const requestOptions = await this.pppAnalysisRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * PPP over time: how a country\'s purchasing-power-parity factor changed, comparing countries, or \'movers\'. Growth plan or higher.
     * PPP analysis
     */
    async pppAnalysis(requestParameters: PppAnalysisRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PppAnalysisResponse> {
        const response = await this.pppAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rates without sending the request
     */
    async ratesRequestOpts(requestParameters: RatesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/rates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The full exchange-rate snapshot for a date (USD base).
     * Rates
     */
    async ratesRaw(requestParameters: RatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatesResponse>> {
        const requestOptions = await this.ratesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * The full exchange-rate snapshot for a date (USD base).
     * Rates
     */
    async rates(requestParameters: RatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatesResponse> {
        const response = await this.ratesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ratesByBase without sending the request
     */
    async ratesByBaseRequestOpts(requestParameters: RatesByBaseRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['base'] == null) {
            throw new runtime.RequiredError(
                'base',
                'Required parameter "base" was null or undefined when calling ratesByBase().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/rates/{base}`;
        urlPath = urlPath.replace('{base}', encodeURIComponent(String(requestParameters['base'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The same snapshot re-expressed against any base currency.
     * Rates by base
     */
    async ratesByBaseRaw(requestParameters: RatesByBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatesByBaseResponse>> {
        const requestOptions = await this.ratesByBaseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * The same snapshot re-expressed against any base currency.
     * Rates by base
     */
    async ratesByBase(requestParameters: RatesByBaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatesByBaseResponse> {
        const response = await this.ratesByBaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for safeHaven without sending the request
     */
    async safeHavenRequestOpts(requestParameters: SafeHavenRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['currencies'] != null) {
            queryParameters['currencies'] = requestParameters['currencies'];
        }

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/safe-haven`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ranks currencies by a composite safe-haven score (low volatility + shallow drawdown + 2008-crisis resilience). Growth plan or higher.
     * Safe haven
     */
    async safeHavenRaw(requestParameters: SafeHavenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SafeHavenResponse>> {
        const requestOptions = await this.safeHavenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Ranks currencies by a composite safe-haven score (low volatility + shallow drawdown + 2008-crisis resilience). Growth plan or higher.
     * Safe haven
     */
    async safeHaven(requestParameters: SafeHavenRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SafeHavenResponse> {
        const response = await this.safeHavenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for volatility without sending the request
     */
    async volatilityRequestOpts(requestParameters: VolatilityRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['base'] != null) {
            queryParameters['base'] = requestParameters['base'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['universe'] != null) {
            queryParameters['universe'] = requestParameters['universe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/volatility`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Annualized volatility of a currency vs a base, or a stability ranking of the liquid currencies. Growth plan or higher.
     * Volatility
     */
    async volatilityRaw(requestParameters: VolatilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VolatilityResponse>> {
        const requestOptions = await this.volatilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Annualized volatility of a currency vs a base, or a stability ranking of the liquid currencies. Growth plan or higher.
     * Volatility
     */
    async volatility(requestParameters: VolatilityRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VolatilityResponse> {
        const response = await this.volatilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
