/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiResponse
 */
export interface AiResponse {
    /**
     * 
     * @type {string}
     * @memberof AiResponse
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof AiResponse
     */
    answer: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof AiResponse
     */
    data: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof AiResponse
     */
    toolCalls?: number;
}

/**
 * Check if a given object implements the AiResponse interface.
 */
export function instanceOfAiResponse(value: object): value is AiResponse {
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AiResponseFromJSON(json: any): AiResponse {
    return AiResponseFromJSONTyped(json, false);
}

export function AiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'answer': json['answer'],
        'data': json['data'],
        'toolCalls': json['toolCalls'] == null ? undefined : json['toolCalls'],
    };
}

export function AiResponseToJSON(json: any): AiResponse {
    return AiResponseToJSONTyped(json, false);
}

export function AiResponseToJSONTyped(value?: AiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'answer': value['answer'],
        'data': value['data'],
        'toolCalls': value['toolCalls'],
    };
}

