/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiErrorError
 */
export interface ApiErrorError {
    /**
     * 
     * @type {string}
     * @memberof ApiErrorError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorError
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof ApiErrorError
     */
    details?: any | null;
}

/**
 * Check if a given object implements the ApiErrorError interface.
 */
export function instanceOfApiErrorError(value: object): value is ApiErrorError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiErrorErrorFromJSON(json: any): ApiErrorError {
    return ApiErrorErrorFromJSONTyped(json, false);
}

export function ApiErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ApiErrorErrorToJSON(json: any): ApiErrorError {
    return ApiErrorErrorToJSONTyped(json, false);
}

export function ApiErrorErrorToJSONTyped(value?: ApiErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

