/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertResponseResultsInnerPppAnyOf
 */
export interface ConvertResponseResultsInnerPppAnyOf {
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPppAnyOf
     */
    fromFactor: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPppAnyOf
     */
    toFactor: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPppAnyOf
     */
    result: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPppAnyOf
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInnerPppAnyOf
     */
    source: string;
}

/**
 * Check if a given object implements the ConvertResponseResultsInnerPppAnyOf interface.
 */
export function instanceOfConvertResponseResultsInnerPppAnyOf(value: object): value is ConvertResponseResultsInnerPppAnyOf {
    if (!('fromFactor' in value) || value['fromFactor'] === undefined) return false;
    if (!('toFactor' in value) || value['toFactor'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function ConvertResponseResultsInnerPppAnyOfFromJSON(json: any): ConvertResponseResultsInnerPppAnyOf {
    return ConvertResponseResultsInnerPppAnyOfFromJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertResponseResultsInnerPppAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'fromFactor': json['fromFactor'],
        'toFactor': json['toFactor'],
        'result': json['result'],
        'year': json['year'],
        'source': json['source'],
    };
}

export function ConvertResponseResultsInnerPppAnyOfToJSON(json: any): ConvertResponseResultsInnerPppAnyOf {
    return ConvertResponseResultsInnerPppAnyOfToJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppAnyOfToJSONTyped(value?: ConvertResponseResultsInnerPppAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromFactor': value['fromFactor'],
        'toFactor': value['toFactor'],
        'result': value['result'],
        'year': value['year'],
        'source': value['source'],
    };
}

