/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConvertResponseResultsInner } from './ConvertResponseResultsInner';
import {
    ConvertResponseResultsInnerFromJSON,
    ConvertResponseResultsInnerFromJSONTyped,
    ConvertResponseResultsInnerToJSON,
    ConvertResponseResultsInnerToJSONTyped,
} from './ConvertResponseResultsInner';

/**
 * 
 * @export
 * @interface ConvertResponse
 */
export interface ConvertResponse {
    /**
     * 
     * @type {string}
     * @memberof ConvertResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponse
     */
    fromCountry?: string;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponse
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponse
     */
    requestedDate?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConvertResponse
     */
    asOf?: { [key: string]: string; };
    /**
     * 
     * @type {Array<ConvertResponseResultsInner>}
     * @memberof ConvertResponse
     */
    results: Array<ConvertResponseResultsInner>;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ConvertResponse interface.
 */
export function instanceOfConvertResponse(value: object): value is ConvertResponse {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ConvertResponseFromJSON(json: any): ConvertResponse {
    return ConvertResponseFromJSONTyped(json, false);
}

export function ConvertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'fromCountry': json['fromCountry'] == null ? undefined : json['fromCountry'],
        'amount': json['amount'],
        'date': json['date'],
        'requestedDate': json['requestedDate'] == null ? undefined : json['requestedDate'],
        'asOf': json['asOf'] == null ? undefined : json['asOf'],
        'results': ((json['results'] as Array<any>).map(ConvertResponseResultsInnerFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ConvertResponseToJSON(json: any): ConvertResponse {
    return ConvertResponseToJSONTyped(json, false);
}

export function ConvertResponseToJSONTyped(value?: ConvertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'fromCountry': value['fromCountry'],
        'amount': value['amount'],
        'date': value['date'],
        'requestedDate': value['requestedDate'],
        'asOf': value['asOf'],
        'results': ((value['results'] as Array<any>).map(ConvertResponseResultsInnerToJSON)),
        'message': value['message'],
    };
}

