/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConvertResponseResultsInnerPpp } from './ConvertResponseResultsInnerPpp';
import {
    ConvertResponseResultsInnerPppFromJSON,
    ConvertResponseResultsInnerPppFromJSONTyped,
    ConvertResponseResultsInnerPppToJSON,
    ConvertResponseResultsInnerPppToJSONTyped,
} from './ConvertResponseResultsInnerPpp';

/**
 * 
 * @export
 * @interface ConvertResponseResultsInner
 */
export interface ConvertResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInner
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInner
     */
    toCountry?: string;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInner
     */
    result: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInner
     */
    rate: number;
    /**
     * 
     * @type {ConvertResponseResultsInnerPpp}
     * @memberof ConvertResponseResultsInner
     */
    ppp?: ConvertResponseResultsInnerPpp;
}

/**
 * Check if a given object implements the ConvertResponseResultsInner interface.
 */
export function instanceOfConvertResponseResultsInner(value: object): value is ConvertResponseResultsInner {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    return true;
}

export function ConvertResponseResultsInnerFromJSON(json: any): ConvertResponseResultsInner {
    return ConvertResponseResultsInnerFromJSONTyped(json, false);
}

export function ConvertResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'toCountry': json['toCountry'] == null ? undefined : json['toCountry'],
        'result': json['result'],
        'rate': json['rate'],
        'ppp': json['ppp'] == null ? undefined : ConvertResponseResultsInnerPppFromJSON(json['ppp']),
    };
}

export function ConvertResponseResultsInnerToJSON(json: any): ConvertResponseResultsInner {
    return ConvertResponseResultsInnerToJSONTyped(json, false);
}

export function ConvertResponseResultsInnerToJSONTyped(value?: ConvertResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'toCountry': value['toCountry'],
        'result': value['result'],
        'rate': value['rate'],
        'ppp': ConvertResponseResultsInnerPppToJSON(value['ppp']),
    };
}

