/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConvertResponseResultsInnerPppAnyOf } from './ConvertResponseResultsInnerPppAnyOf';
import {
    ConvertResponseResultsInnerPppAnyOfFromJSON,
    ConvertResponseResultsInnerPppAnyOfFromJSONTyped,
    ConvertResponseResultsInnerPppAnyOfToJSON,
    ConvertResponseResultsInnerPppAnyOfToJSONTyped,
} from './ConvertResponseResultsInnerPppAnyOf';
import type { ConvertResponseResultsInnerPppAnyOf1 } from './ConvertResponseResultsInnerPppAnyOf1';
import {
    ConvertResponseResultsInnerPppAnyOf1FromJSON,
    ConvertResponseResultsInnerPppAnyOf1FromJSONTyped,
    ConvertResponseResultsInnerPppAnyOf1ToJSON,
    ConvertResponseResultsInnerPppAnyOf1ToJSONTyped,
} from './ConvertResponseResultsInnerPppAnyOf1';

/**
 * 
 * @export
 * @interface ConvertResponseResultsInnerPpp
 */
export interface ConvertResponseResultsInnerPpp {
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPpp
     */
    fromFactor: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPpp
     */
    toFactor: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPpp
     */
    result: number;
    /**
     * 
     * @type {number}
     * @memberof ConvertResponseResultsInnerPpp
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInnerPpp
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInnerPpp
     */
    error: string;
}

/**
 * Check if a given object implements the ConvertResponseResultsInnerPpp interface.
 */
export function instanceOfConvertResponseResultsInnerPpp(value: object): value is ConvertResponseResultsInnerPpp {
    if (!('fromFactor' in value) || value['fromFactor'] === undefined) return false;
    if (!('toFactor' in value) || value['toFactor'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ConvertResponseResultsInnerPppFromJSON(json: any): ConvertResponseResultsInnerPpp {
    return ConvertResponseResultsInnerPppFromJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertResponseResultsInnerPpp {
    if (json == null) {
        return json;
    }
    return {
        
        'fromFactor': json['fromFactor'],
        'toFactor': json['toFactor'],
        'result': json['result'],
        'year': json['year'],
        'source': json['source'],
        'error': json['error'],
    };
}

export function ConvertResponseResultsInnerPppToJSON(json: any): ConvertResponseResultsInnerPpp {
    return ConvertResponseResultsInnerPppToJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppToJSONTyped(value?: ConvertResponseResultsInnerPpp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromFactor': value['fromFactor'],
        'toFactor': value['toFactor'],
        'result': value['result'],
        'year': value['year'],
        'source': value['source'],
        'error': value['error'],
    };
}

