/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertResponseResultsInnerPppAnyOf1
 */
export interface ConvertResponseResultsInnerPppAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof ConvertResponseResultsInnerPppAnyOf1
     */
    error: string;
}

/**
 * Check if a given object implements the ConvertResponseResultsInnerPppAnyOf1 interface.
 */
export function instanceOfConvertResponseResultsInnerPppAnyOf1(value: object): value is ConvertResponseResultsInnerPppAnyOf1 {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ConvertResponseResultsInnerPppAnyOf1FromJSON(json: any): ConvertResponseResultsInnerPppAnyOf1 {
    return ConvertResponseResultsInnerPppAnyOf1FromJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertResponseResultsInnerPppAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ConvertResponseResultsInnerPppAnyOf1ToJSON(json: any): ConvertResponseResultsInnerPppAnyOf1 {
    return ConvertResponseResultsInnerPppAnyOf1ToJSONTyped(json, false);
}

export function ConvertResponseResultsInnerPppAnyOf1ToJSONTyped(value?: ConvertResponseResultsInnerPppAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

