/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorrelationResponseResultsInner
 */
export interface CorrelationResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof CorrelationResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof CorrelationResponseResultsInner
     */
    correlation: number | null;
    /**
     * 
     * @type {number}
     * @memberof CorrelationResponseResultsInner
     */
    observations: number;
    /**
     * 
     * @type {string}
     * @memberof CorrelationResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the CorrelationResponseResultsInner interface.
 */
export function instanceOfCorrelationResponseResultsInner(value: object): value is CorrelationResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('correlation' in value) || value['correlation'] === undefined) return false;
    if (!('observations' in value) || value['observations'] === undefined) return false;
    return true;
}

export function CorrelationResponseResultsInnerFromJSON(json: any): CorrelationResponseResultsInner {
    return CorrelationResponseResultsInnerFromJSONTyped(json, false);
}

export function CorrelationResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrelationResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'correlation': json['correlation'],
        'observations': json['observations'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CorrelationResponseResultsInnerToJSON(json: any): CorrelationResponseResultsInner {
    return CorrelationResponseResultsInnerToJSONTyped(json, false);
}

export function CorrelationResponseResultsInnerToJSONTyped(value?: CorrelationResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'correlation': value['correlation'],
        'observations': value['observations'],
        'note': value['note'],
    };
}

