/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorrelationResponseResultsInner } from './CorrelationResponseResultsInner';
import {
    CorrelationResponseResultsInnerFromJSON,
    CorrelationResponseResultsInnerFromJSONTyped,
    CorrelationResponseResultsInnerToJSON,
    CorrelationResponseResultsInnerToJSONTyped,
} from './CorrelationResponseResultsInner';

/**
 * 
 * @export
 * @interface CorrelationResponse
 */
export interface CorrelationResponse {
    /**
     * 
     * @type {string}
     * @memberof CorrelationResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof CorrelationResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof CorrelationResponse
     */
    to: string;
    /**
     * 
     * @type {Array<CorrelationResponseResultsInner>}
     * @memberof CorrelationResponse
     */
    results: Array<CorrelationResponseResultsInner>;
}

/**
 * Check if a given object implements the CorrelationResponse interface.
 */
export function instanceOfCorrelationResponse(value: object): value is CorrelationResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function CorrelationResponseFromJSON(json: any): CorrelationResponse {
    return CorrelationResponseFromJSONTyped(json, false);
}

export function CorrelationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrelationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'results': ((json['results'] as Array<any>).map(CorrelationResponseResultsInnerFromJSON)),
    };
}

export function CorrelationResponseToJSON(json: any): CorrelationResponse {
    return CorrelationResponseToJSONTyped(json, false);
}

export function CorrelationResponseToJSONTyped(value?: CorrelationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'results': ((value['results'] as Array<any>).map(CorrelationResponseResultsInnerToJSON)),
    };
}

