/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountriesResponseInner
 */
export interface CountriesResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CountriesResponseInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CountriesResponseInner
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CountriesResponseInner
     */
    currencies?: Array<string>;
}

/**
 * Check if a given object implements the CountriesResponseInner interface.
 */
export function instanceOfCountriesResponseInner(value: object): value is CountriesResponseInner {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CountriesResponseInnerFromJSON(json: any): CountriesResponseInner {
    return CountriesResponseInnerFromJSONTyped(json, false);
}

export function CountriesResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountriesResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'currencies': json['currencies'] == null ? undefined : json['currencies'],
    };
}

export function CountriesResponseInnerToJSON(json: any): CountriesResponseInner {
    return CountriesResponseInnerToJSONTyped(json, false);
}

export function CountriesResponseInnerToJSONTyped(value?: CountriesResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'currencies': value['currencies'],
    };
}

