/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrenciesResponseInner
 */
export interface CurrenciesResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CurrenciesResponseInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesResponseInner
     */
    numeric: string;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesResponseInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesResponseInner
     */
    symbol: string;
}

/**
 * Check if a given object implements the CurrenciesResponseInner interface.
 */
export function instanceOfCurrenciesResponseInner(value: object): value is CurrenciesResponseInner {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('numeric' in value) || value['numeric'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function CurrenciesResponseInnerFromJSON(json: any): CurrenciesResponseInner {
    return CurrenciesResponseInnerFromJSONTyped(json, false);
}

export function CurrenciesResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrenciesResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'numeric': json['numeric'],
        'name': json['name'],
        'symbol': json['symbol'],
    };
}

export function CurrenciesResponseInnerToJSON(json: any): CurrenciesResponseInner {
    return CurrenciesResponseInnerToJSONTyped(json, false);
}

export function CurrenciesResponseInnerToJSONTyped(value?: CurrenciesResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'numeric': value['numeric'],
        'name': value['name'],
        'symbol': value['symbol'],
    };
}

