/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawdownResponseResultsInner } from './DrawdownResponseResultsInner';
import {
    DrawdownResponseResultsInnerFromJSON,
    DrawdownResponseResultsInnerFromJSONTyped,
    DrawdownResponseResultsInnerToJSON,
    DrawdownResponseResultsInnerToJSONTyped,
} from './DrawdownResponseResultsInner';

/**
 * 
 * @export
 * @interface DrawdownResponse
 */
export interface DrawdownResponse {
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponse
     */
    to: string;
    /**
     * 
     * @type {DrawdownResponseModeEnum}
     * @memberof DrawdownResponse
     */
    mode: DrawdownResponseModeEnum;
    /**
     * 
     * @type {DrawdownResponseSortEnum}
     * @memberof DrawdownResponse
     */
    sort?: DrawdownResponseSortEnum;
    /**
     * 
     * @type {DrawdownResponseUniverseEnum}
     * @memberof DrawdownResponse
     */
    universe?: DrawdownResponseUniverseEnum;
    /**
     * 
     * @type {Array<DrawdownResponseResultsInner>}
     * @memberof DrawdownResponse
     */
    results: Array<DrawdownResponseResultsInner>;
}


/**
 * @export
 */
export const DrawdownResponseModeEnum = {
    Compare: 'compare',
    Ranking: 'ranking'
} as const;
export type DrawdownResponseModeEnum = typeof DrawdownResponseModeEnum[keyof typeof DrawdownResponseModeEnum];

/**
 * @export
 */
export const DrawdownResponseSortEnum = {
    Deepest: 'deepest',
    Recovery: 'recovery'
} as const;
export type DrawdownResponseSortEnum = typeof DrawdownResponseSortEnum[keyof typeof DrawdownResponseSortEnum];

/**
 * @export
 */
export const DrawdownResponseUniverseEnum = {
    Liquid: 'liquid',
    Majors: 'majors'
} as const;
export type DrawdownResponseUniverseEnum = typeof DrawdownResponseUniverseEnum[keyof typeof DrawdownResponseUniverseEnum];


/**
 * Check if a given object implements the DrawdownResponse interface.
 */
export function instanceOfDrawdownResponse(value: object): value is DrawdownResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function DrawdownResponseFromJSON(json: any): DrawdownResponse {
    return DrawdownResponseFromJSONTyped(json, false);
}

export function DrawdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'mode': json['mode'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'universe': json['universe'] == null ? undefined : json['universe'],
        'results': ((json['results'] as Array<any>).map(DrawdownResponseResultsInnerFromJSON)),
    };
}

export function DrawdownResponseToJSON(json: any): DrawdownResponse {
    return DrawdownResponseToJSONTyped(json, false);
}

export function DrawdownResponseToJSONTyped(value?: DrawdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'mode': value['mode'],
        'sort': value['sort'],
        'universe': value['universe'],
        'results': ((value['results'] as Array<any>).map(DrawdownResponseResultsInnerToJSON)),
    };
}

