/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrawdownResponseResultsInner
 */
export interface DrawdownResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof DrawdownResponseResultsInner
     */
    maxDrawdownPct: number | null;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponseResultsInner
     */
    peakDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponseResultsInner
     */
    troughDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponseResultsInner
     */
    recoveryDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DrawdownResponseResultsInner
     */
    recoveryDays?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DrawdownResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the DrawdownResponseResultsInner interface.
 */
export function instanceOfDrawdownResponseResultsInner(value: object): value is DrawdownResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('maxDrawdownPct' in value) || value['maxDrawdownPct'] === undefined) return false;
    return true;
}

export function DrawdownResponseResultsInnerFromJSON(json: any): DrawdownResponseResultsInner {
    return DrawdownResponseResultsInnerFromJSONTyped(json, false);
}

export function DrawdownResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawdownResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'maxDrawdownPct': json['maxDrawdownPct'],
        'peakDate': json['peakDate'] == null ? undefined : json['peakDate'],
        'troughDate': json['troughDate'] == null ? undefined : json['troughDate'],
        'recoveryDate': json['recoveryDate'] == null ? undefined : json['recoveryDate'],
        'recoveryDays': json['recoveryDays'] == null ? undefined : json['recoveryDays'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function DrawdownResponseResultsInnerToJSON(json: any): DrawdownResponseResultsInner {
    return DrawdownResponseResultsInnerToJSONTyped(json, false);
}

export function DrawdownResponseResultsInnerToJSONTyped(value?: DrawdownResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'maxDrawdownPct': value['maxDrawdownPct'],
        'peakDate': value['peakDate'],
        'troughDate': value['troughDate'],
        'recoveryDate': value['recoveryDate'],
        'recoveryDays': value['recoveryDays'],
        'note': value['note'],
    };
}

