/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryAnalysisResponseResultsInnerStats
 */
export interface HistoryAnalysisResponseResultsInnerStats {
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInnerStats
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInnerStats
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInnerStats
     */
    avg: number;
}

/**
 * Check if a given object implements the HistoryAnalysisResponseResultsInnerStats interface.
 */
export function instanceOfHistoryAnalysisResponseResultsInnerStats(value: object): value is HistoryAnalysisResponseResultsInnerStats {
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('avg' in value) || value['avg'] === undefined) return false;
    return true;
}

export function HistoryAnalysisResponseResultsInnerStatsFromJSON(json: any): HistoryAnalysisResponseResultsInnerStats {
    return HistoryAnalysisResponseResultsInnerStatsFromJSONTyped(json, false);
}

export function HistoryAnalysisResponseResultsInnerStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryAnalysisResponseResultsInnerStats {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'],
        'max': json['max'],
        'avg': json['avg'],
    };
}

export function HistoryAnalysisResponseResultsInnerStatsToJSON(json: any): HistoryAnalysisResponseResultsInnerStats {
    return HistoryAnalysisResponseResultsInnerStatsToJSONTyped(json, false);
}

export function HistoryAnalysisResponseResultsInnerStatsToJSONTyped(value?: HistoryAnalysisResponseResultsInnerStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
        'avg': value['avg'],
    };
}

