/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryAnalysisResponseResultsInner } from './HistoryAnalysisResponseResultsInner';
import {
    HistoryAnalysisResponseResultsInnerFromJSON,
    HistoryAnalysisResponseResultsInnerFromJSONTyped,
    HistoryAnalysisResponseResultsInnerToJSON,
    HistoryAnalysisResponseResultsInnerToJSONTyped,
} from './HistoryAnalysisResponseResultsInner';

/**
 * 
 * @export
 * @interface HistoryAnalysisResponse
 */
export interface HistoryAnalysisResponse {
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponse
     */
    to: string;
    /**
     * 
     * @type {HistoryAnalysisResponseModeEnum}
     * @memberof HistoryAnalysisResponse
     */
    mode: HistoryAnalysisResponseModeEnum;
    /**
     * 
     * @type {HistoryAnalysisResponseSortEnum}
     * @memberof HistoryAnalysisResponse
     */
    sort?: HistoryAnalysisResponseSortEnum;
    /**
     * 
     * @type {HistoryAnalysisResponseAssetClassEnum}
     * @memberof HistoryAnalysisResponse
     */
    assetClass?: HistoryAnalysisResponseAssetClassEnum;
    /**
     * 
     * @type {HistoryAnalysisResponseIntervalEnum}
     * @memberof HistoryAnalysisResponse
     */
    interval?: HistoryAnalysisResponseIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryAnalysisResponse
     */
    stats: boolean;
    /**
     * 
     * @type {Array<HistoryAnalysisResponseResultsInner>}
     * @memberof HistoryAnalysisResponse
     */
    results: Array<HistoryAnalysisResponseResultsInner>;
}


/**
 * @export
 */
export const HistoryAnalysisResponseModeEnum = {
    Compare: 'compare',
    Movers: 'movers'
} as const;
export type HistoryAnalysisResponseModeEnum = typeof HistoryAnalysisResponseModeEnum[keyof typeof HistoryAnalysisResponseModeEnum];

/**
 * @export
 */
export const HistoryAnalysisResponseSortEnum = {
    Strengthened: 'strengthened',
    Weakened: 'weakened'
} as const;
export type HistoryAnalysisResponseSortEnum = typeof HistoryAnalysisResponseSortEnum[keyof typeof HistoryAnalysisResponseSortEnum];

/**
 * @export
 */
export const HistoryAnalysisResponseAssetClassEnum = {
    Fiat: 'fiat',
    Metals: 'metals',
    All: 'all',
    Crypto: 'crypto'
} as const;
export type HistoryAnalysisResponseAssetClassEnum = typeof HistoryAnalysisResponseAssetClassEnum[keyof typeof HistoryAnalysisResponseAssetClassEnum];

/**
 * @export
 */
export const HistoryAnalysisResponseIntervalEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type HistoryAnalysisResponseIntervalEnum = typeof HistoryAnalysisResponseIntervalEnum[keyof typeof HistoryAnalysisResponseIntervalEnum];


/**
 * Check if a given object implements the HistoryAnalysisResponse interface.
 */
export function instanceOfHistoryAnalysisResponse(value: object): value is HistoryAnalysisResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function HistoryAnalysisResponseFromJSON(json: any): HistoryAnalysisResponse {
    return HistoryAnalysisResponseFromJSONTyped(json, false);
}

export function HistoryAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'mode': json['mode'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'assetClass': json['assetClass'] == null ? undefined : json['assetClass'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'stats': json['stats'],
        'results': ((json['results'] as Array<any>).map(HistoryAnalysisResponseResultsInnerFromJSON)),
    };
}

export function HistoryAnalysisResponseToJSON(json: any): HistoryAnalysisResponse {
    return HistoryAnalysisResponseToJSONTyped(json, false);
}

export function HistoryAnalysisResponseToJSONTyped(value?: HistoryAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'mode': value['mode'],
        'sort': value['sort'],
        'assetClass': value['assetClass'],
        'interval': value['interval'],
        'stats': value['stats'],
        'results': ((value['results'] as Array<any>).map(HistoryAnalysisResponseResultsInnerToJSON)),
    };
}

