/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryAnalysisResponseResultsInnerStats } from './HistoryAnalysisResponseResultsInnerStats';
import {
    HistoryAnalysisResponseResultsInnerStatsFromJSON,
    HistoryAnalysisResponseResultsInnerStatsFromJSONTyped,
    HistoryAnalysisResponseResultsInnerStatsToJSON,
    HistoryAnalysisResponseResultsInnerStatsToJSONTyped,
} from './HistoryAnalysisResponseResultsInnerStats';

/**
 * 
 * @export
 * @interface HistoryAnalysisResponseResultsInner
 */
export interface HistoryAnalysisResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    endDate: string;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    startRate: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    endRate: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    changePct: number | null;
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    strengthenedPct: number | null;
    /**
     * 
     * @type {HistoryAnalysisResponseResultsInnerStats}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    stats?: HistoryAnalysisResponseResultsInnerStats;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    series?: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    volatility?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HistoryAnalysisResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the HistoryAnalysisResponseResultsInner interface.
 */
export function instanceOfHistoryAnalysisResponseResultsInner(value: object): value is HistoryAnalysisResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('startRate' in value) || value['startRate'] === undefined) return false;
    if (!('endRate' in value) || value['endRate'] === undefined) return false;
    if (!('changePct' in value) || value['changePct'] === undefined) return false;
    if (!('strengthenedPct' in value) || value['strengthenedPct'] === undefined) return false;
    return true;
}

export function HistoryAnalysisResponseResultsInnerFromJSON(json: any): HistoryAnalysisResponseResultsInner {
    return HistoryAnalysisResponseResultsInnerFromJSONTyped(json, false);
}

export function HistoryAnalysisResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryAnalysisResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'startDate': json['startDate'],
        'endDate': json['endDate'],
        'startRate': json['startRate'],
        'endRate': json['endRate'],
        'changePct': json['changePct'],
        'strengthenedPct': json['strengthenedPct'],
        'stats': json['stats'] == null ? undefined : HistoryAnalysisResponseResultsInnerStatsFromJSON(json['stats']),
        'series': json['series'] == null ? undefined : json['series'],
        'volatility': json['volatility'] == null ? undefined : json['volatility'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function HistoryAnalysisResponseResultsInnerToJSON(json: any): HistoryAnalysisResponseResultsInner {
    return HistoryAnalysisResponseResultsInnerToJSONTyped(json, false);
}

export function HistoryAnalysisResponseResultsInnerToJSONTyped(value?: HistoryAnalysisResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'startDate': value['startDate'],
        'endDate': value['endDate'],
        'startRate': value['startRate'],
        'endRate': value['endRate'],
        'changePct': value['changePct'],
        'strengthenedPct': value['strengthenedPct'],
        'stats': HistoryAnalysisResponseResultsInnerStatsToJSON(value['stats']),
        'series': value['series'],
        'volatility': value['volatility'],
        'note': value['note'],
    };
}

