/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryResponse
 */
export interface HistoryResponse {
    /**
     * 
     * @type {string}
     * @memberof HistoryResponse
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryResponse
     */
    base: string;
    /**
     * 
     * @type {HistoryResponseIntervalEnum}
     * @memberof HistoryResponse
     */
    interval: HistoryResponseIntervalEnum;
    /**
     * 
     * @type {string}
     * @memberof HistoryResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryResponse
     */
    to: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof HistoryResponse
     */
    rates: { [key: string]: number; };
}


/**
 * @export
 */
export const HistoryResponseIntervalEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type HistoryResponseIntervalEnum = typeof HistoryResponseIntervalEnum[keyof typeof HistoryResponseIntervalEnum];


/**
 * Check if a given object implements the HistoryResponse interface.
 */
export function instanceOfHistoryResponse(value: object): value is HistoryResponse {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('rates' in value) || value['rates'] === undefined) return false;
    return true;
}

export function HistoryResponseFromJSON(json: any): HistoryResponse {
    return HistoryResponseFromJSONTyped(json, false);
}

export function HistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'base': json['base'],
        'interval': json['interval'],
        'from': json['from'],
        'to': json['to'],
        'rates': json['rates'],
    };
}

export function HistoryResponseToJSON(json: any): HistoryResponse {
    return HistoryResponseToJSONTyped(json, false);
}

export function HistoryResponseToJSONTyped(value?: HistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'base': value['base'],
        'interval': value['interval'],
        'from': value['from'],
        'to': value['to'],
        'rates': value['rates'],
    };
}

