/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MeanReversionResponseResultsInner } from './MeanReversionResponseResultsInner';
import {
    MeanReversionResponseResultsInnerFromJSON,
    MeanReversionResponseResultsInnerFromJSONTyped,
    MeanReversionResponseResultsInnerToJSON,
    MeanReversionResponseResultsInnerToJSONTyped,
} from './MeanReversionResponseResultsInner';

/**
 * 
 * @export
 * @interface MeanReversionResponse
 */
export interface MeanReversionResponse {
    /**
     * 
     * @type {string}
     * @memberof MeanReversionResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof MeanReversionResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof MeanReversionResponse
     */
    to: string;
    /**
     * 
     * @type {MeanReversionResponseUniverseEnum}
     * @memberof MeanReversionResponse
     */
    universe?: MeanReversionResponseUniverseEnum;
    /**
     * 
     * @type {Array<MeanReversionResponseResultsInner>}
     * @memberof MeanReversionResponse
     */
    results: Array<MeanReversionResponseResultsInner>;
}


/**
 * @export
 */
export const MeanReversionResponseUniverseEnum = {
    Liquid: 'liquid',
    Majors: 'majors'
} as const;
export type MeanReversionResponseUniverseEnum = typeof MeanReversionResponseUniverseEnum[keyof typeof MeanReversionResponseUniverseEnum];


/**
 * Check if a given object implements the MeanReversionResponse interface.
 */
export function instanceOfMeanReversionResponse(value: object): value is MeanReversionResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MeanReversionResponseFromJSON(json: any): MeanReversionResponse {
    return MeanReversionResponseFromJSONTyped(json, false);
}

export function MeanReversionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeanReversionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'universe': json['universe'] == null ? undefined : json['universe'],
        'results': ((json['results'] as Array<any>).map(MeanReversionResponseResultsInnerFromJSON)),
    };
}

export function MeanReversionResponseToJSON(json: any): MeanReversionResponse {
    return MeanReversionResponseToJSONTyped(json, false);
}

export function MeanReversionResponseToJSONTyped(value?: MeanReversionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'universe': value['universe'],
        'results': ((value['results'] as Array<any>).map(MeanReversionResponseResultsInnerToJSON)),
    };
}

