/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeanReversionResponseResultsInner
 */
export interface MeanReversionResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof MeanReversionResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof MeanReversionResponseResultsInner
     */
    score: number | null;
    /**
     * 
     * @type {number}
     * @memberof MeanReversionResponseResultsInner
     */
    deviationPct: number | null;
    /**
     * 
     * @type {number}
     * @memberof MeanReversionResponseResultsInner
     */
    reversionFrequency: number | null;
    /**
     * 
     * @type {number}
     * @memberof MeanReversionResponseResultsInner
     */
    halfLifeDays: number | null;
    /**
     * 
     * @type {string}
     * @memberof MeanReversionResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the MeanReversionResponseResultsInner interface.
 */
export function instanceOfMeanReversionResponseResultsInner(value: object): value is MeanReversionResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('deviationPct' in value) || value['deviationPct'] === undefined) return false;
    if (!('reversionFrequency' in value) || value['reversionFrequency'] === undefined) return false;
    if (!('halfLifeDays' in value) || value['halfLifeDays'] === undefined) return false;
    return true;
}

export function MeanReversionResponseResultsInnerFromJSON(json: any): MeanReversionResponseResultsInner {
    return MeanReversionResponseResultsInnerFromJSONTyped(json, false);
}

export function MeanReversionResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeanReversionResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'score': json['score'],
        'deviationPct': json['deviationPct'],
        'reversionFrequency': json['reversionFrequency'],
        'halfLifeDays': json['halfLifeDays'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function MeanReversionResponseResultsInnerToJSON(json: any): MeanReversionResponseResultsInner {
    return MeanReversionResponseResultsInnerToJSONTyped(json, false);
}

export function MeanReversionResponseResultsInnerToJSONTyped(value?: MeanReversionResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'score': value['score'],
        'deviationPct': value['deviationPct'],
        'reversionFrequency': value['reversionFrequency'],
        'halfLifeDays': value['halfLifeDays'],
        'note': value['note'],
    };
}

