/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryAnalysisResponseResultsInnerStats } from './HistoryAnalysisResponseResultsInnerStats';
import {
    HistoryAnalysisResponseResultsInnerStatsFromJSON,
    HistoryAnalysisResponseResultsInnerStatsFromJSONTyped,
    HistoryAnalysisResponseResultsInnerStatsToJSON,
    HistoryAnalysisResponseResultsInnerStatsToJSONTyped,
} from './HistoryAnalysisResponseResultsInnerStats';

/**
 * 
 * @export
 * @interface PppAnalysisResponseResultsInner
 */
export interface PppAnalysisResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof PppAnalysisResponseResultsInner
     */
    country: string;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponseResultsInner
     */
    startYear: number;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponseResultsInner
     */
    endYear: number;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponseResultsInner
     */
    startFactor: number | null;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponseResultsInner
     */
    endFactor: number | null;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponseResultsInner
     */
    changePct: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PppAnalysisResponseResultsInner
     */
    projected: boolean;
    /**
     * 
     * @type {HistoryAnalysisResponseResultsInnerStats}
     * @memberof PppAnalysisResponseResultsInner
     */
    stats?: HistoryAnalysisResponseResultsInnerStats;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof PppAnalysisResponseResultsInner
     */
    series?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof PppAnalysisResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the PppAnalysisResponseResultsInner interface.
 */
export function instanceOfPppAnalysisResponseResultsInner(value: object): value is PppAnalysisResponseResultsInner {
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('startYear' in value) || value['startYear'] === undefined) return false;
    if (!('endYear' in value) || value['endYear'] === undefined) return false;
    if (!('startFactor' in value) || value['startFactor'] === undefined) return false;
    if (!('endFactor' in value) || value['endFactor'] === undefined) return false;
    if (!('changePct' in value) || value['changePct'] === undefined) return false;
    if (!('projected' in value) || value['projected'] === undefined) return false;
    return true;
}

export function PppAnalysisResponseResultsInnerFromJSON(json: any): PppAnalysisResponseResultsInner {
    return PppAnalysisResponseResultsInnerFromJSONTyped(json, false);
}

export function PppAnalysisResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PppAnalysisResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'],
        'startYear': json['startYear'],
        'endYear': json['endYear'],
        'startFactor': json['startFactor'],
        'endFactor': json['endFactor'],
        'changePct': json['changePct'],
        'projected': json['projected'],
        'stats': json['stats'] == null ? undefined : HistoryAnalysisResponseResultsInnerStatsFromJSON(json['stats']),
        'series': json['series'] == null ? undefined : json['series'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PppAnalysisResponseResultsInnerToJSON(json: any): PppAnalysisResponseResultsInner {
    return PppAnalysisResponseResultsInnerToJSONTyped(json, false);
}

export function PppAnalysisResponseResultsInnerToJSONTyped(value?: PppAnalysisResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'startYear': value['startYear'],
        'endYear': value['endYear'],
        'startFactor': value['startFactor'],
        'endFactor': value['endFactor'],
        'changePct': value['changePct'],
        'projected': value['projected'],
        'stats': HistoryAnalysisResponseResultsInnerStatsToJSON(value['stats']),
        'series': value['series'],
        'note': value['note'],
    };
}

