/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PppAnalysisResponseResultsInner } from './PppAnalysisResponseResultsInner';
import {
    PppAnalysisResponseResultsInnerFromJSON,
    PppAnalysisResponseResultsInnerFromJSONTyped,
    PppAnalysisResponseResultsInnerToJSON,
    PppAnalysisResponseResultsInnerToJSONTyped,
} from './PppAnalysisResponseResultsInner';

/**
 * 
 * @export
 * @interface PppAnalysisResponse
 */
export interface PppAnalysisResponse {
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponse
     */
    from: number;
    /**
     * 
     * @type {number}
     * @memberof PppAnalysisResponse
     */
    to: number;
    /**
     * 
     * @type {PppAnalysisResponseModeEnum}
     * @memberof PppAnalysisResponse
     */
    mode: PppAnalysisResponseModeEnum;
    /**
     * 
     * @type {PppAnalysisResponseSortEnum}
     * @memberof PppAnalysisResponse
     */
    sort?: PppAnalysisResponseSortEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PppAnalysisResponse
     */
    stats: boolean;
    /**
     * 
     * @type {Array<PppAnalysisResponseResultsInner>}
     * @memberof PppAnalysisResponse
     */
    results: Array<PppAnalysisResponseResultsInner>;
}


/**
 * @export
 */
export const PppAnalysisResponseModeEnum = {
    Compare: 'compare',
    Movers: 'movers'
} as const;
export type PppAnalysisResponseModeEnum = typeof PppAnalysisResponseModeEnum[keyof typeof PppAnalysisResponseModeEnum];

/**
 * @export
 */
export const PppAnalysisResponseSortEnum = {
    Increased: 'increased',
    Decreased: 'decreased'
} as const;
export type PppAnalysisResponseSortEnum = typeof PppAnalysisResponseSortEnum[keyof typeof PppAnalysisResponseSortEnum];


/**
 * Check if a given object implements the PppAnalysisResponse interface.
 */
export function instanceOfPppAnalysisResponse(value: object): value is PppAnalysisResponse {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PppAnalysisResponseFromJSON(json: any): PppAnalysisResponse {
    return PppAnalysisResponseFromJSONTyped(json, false);
}

export function PppAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PppAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'mode': json['mode'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'stats': json['stats'],
        'results': ((json['results'] as Array<any>).map(PppAnalysisResponseResultsInnerFromJSON)),
    };
}

export function PppAnalysisResponseToJSON(json: any): PppAnalysisResponse {
    return PppAnalysisResponseToJSONTyped(json, false);
}

export function PppAnalysisResponseToJSONTyped(value?: PppAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'mode': value['mode'],
        'sort': value['sort'],
        'stats': value['stats'],
        'results': ((value['results'] as Array<any>).map(PppAnalysisResponseResultsInnerToJSON)),
    };
}

