/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatesResponse
 */
export interface RatesResponse {
    /**
     * 
     * @type {string}
     * @memberof RatesResponse
     */
    date: string;
    /**
     * 
     * @type {RatesResponseBaseEnum}
     * @memberof RatesResponse
     */
    base: RatesResponseBaseEnum;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RatesResponse
     */
    rates: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof RatesResponse
     */
    requestedDate?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RatesResponse
     */
    asOf?: { [key: string]: string; };
}


/**
 * @export
 */
export const RatesResponseBaseEnum = {
    Usd: 'USD'
} as const;
export type RatesResponseBaseEnum = typeof RatesResponseBaseEnum[keyof typeof RatesResponseBaseEnum];


/**
 * Check if a given object implements the RatesResponse interface.
 */
export function instanceOfRatesResponse(value: object): value is RatesResponse {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('base' in value) || value['base'] === undefined) return false;
    if (value['base'] !== 'USD') return false;
    
    if (!('rates' in value) || value['rates'] === undefined) return false;
    return true;
}

export function RatesResponseFromJSON(json: any): RatesResponse {
    return RatesResponseFromJSONTyped(json, false);
}

export function RatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'base': json['base'],
        'rates': json['rates'],
        'requestedDate': json['requestedDate'] == null ? undefined : json['requestedDate'],
        'asOf': json['asOf'] == null ? undefined : json['asOf'],
    };
}

export function RatesResponseToJSON(json: any): RatesResponse {
    return RatesResponseToJSONTyped(json, false);
}

export function RatesResponseToJSONTyped(value?: RatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'base': value['base'],
        'rates': value['rates'],
        'requestedDate': value['requestedDate'],
        'asOf': value['asOf'],
    };
}

