/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatesByBaseResponsePpp } from './RatesByBaseResponsePpp';
import {
    RatesByBaseResponsePppFromJSON,
    RatesByBaseResponsePppFromJSONTyped,
    RatesByBaseResponsePppToJSON,
    RatesByBaseResponsePppToJSONTyped,
} from './RatesByBaseResponsePpp';

/**
 * 
 * @export
 * @interface RatesByBaseResponse
 */
export interface RatesByBaseResponse {
    /**
     * 
     * @type {string}
     * @memberof RatesByBaseResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof RatesByBaseResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof RatesByBaseResponse
     */
    requestedDate?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RatesByBaseResponse
     */
    asOf?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RatesByBaseResponse
     */
    rates: { [key: string]: number; };
    /**
     * 
     * @type {RatesByBaseResponsePpp}
     * @memberof RatesByBaseResponse
     */
    ppp?: RatesByBaseResponsePpp;
}

/**
 * Check if a given object implements the RatesByBaseResponse interface.
 */
export function instanceOfRatesByBaseResponse(value: object): value is RatesByBaseResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('rates' in value) || value['rates'] === undefined) return false;
    return true;
}

export function RatesByBaseResponseFromJSON(json: any): RatesByBaseResponse {
    return RatesByBaseResponseFromJSONTyped(json, false);
}

export function RatesByBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesByBaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'date': json['date'],
        'requestedDate': json['requestedDate'] == null ? undefined : json['requestedDate'],
        'asOf': json['asOf'] == null ? undefined : json['asOf'],
        'rates': json['rates'],
        'ppp': json['ppp'] == null ? undefined : RatesByBaseResponsePppFromJSON(json['ppp']),
    };
}

export function RatesByBaseResponseToJSON(json: any): RatesByBaseResponse {
    return RatesByBaseResponseToJSONTyped(json, false);
}

export function RatesByBaseResponseToJSONTyped(value?: RatesByBaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'date': value['date'],
        'requestedDate': value['requestedDate'],
        'asOf': value['asOf'],
        'rates': value['rates'],
        'ppp': RatesByBaseResponsePppToJSON(value['ppp']),
    };
}

