/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatesByBaseResponsePpp
 */
export interface RatesByBaseResponsePpp {
    /**
     * 
     * @type {string}
     * @memberof RatesByBaseResponsePpp
     */
    base: string;
    /**
     * 
     * @type {number}
     * @memberof RatesByBaseResponsePpp
     */
    year: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RatesByBaseResponsePpp
     */
    values: { [key: string]: number; };
}

/**
 * Check if a given object implements the RatesByBaseResponsePpp interface.
 */
export function instanceOfRatesByBaseResponsePpp(value: object): value is RatesByBaseResponsePpp {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function RatesByBaseResponsePppFromJSON(json: any): RatesByBaseResponsePpp {
    return RatesByBaseResponsePppFromJSONTyped(json, false);
}

export function RatesByBaseResponsePppFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesByBaseResponsePpp {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'year': json['year'],
        'values': json['values'],
    };
}

export function RatesByBaseResponsePppToJSON(json: any): RatesByBaseResponsePpp {
    return RatesByBaseResponsePppToJSONTyped(json, false);
}

export function RatesByBaseResponsePppToJSONTyped(value?: RatesByBaseResponsePpp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'year': value['year'],
        'values': value['values'],
    };
}

