/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeHavenResponseResultsInner
 */
export interface SafeHavenResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof SafeHavenResponseResultsInner
     */
    score: number | null;
    /**
     * 
     * @type {number}
     * @memberof SafeHavenResponseResultsInner
     */
    volatility: number | null;
    /**
     * 
     * @type {number}
     * @memberof SafeHavenResponseResultsInner
     */
    maxDrawdownPct: number | null;
    /**
     * 
     * @type {number}
     * @memberof SafeHavenResponseResultsInner
     */
    crisisReturnPct: number | null;
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the SafeHavenResponseResultsInner interface.
 */
export function instanceOfSafeHavenResponseResultsInner(value: object): value is SafeHavenResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('volatility' in value) || value['volatility'] === undefined) return false;
    if (!('maxDrawdownPct' in value) || value['maxDrawdownPct'] === undefined) return false;
    if (!('crisisReturnPct' in value) || value['crisisReturnPct'] === undefined) return false;
    return true;
}

export function SafeHavenResponseResultsInnerFromJSON(json: any): SafeHavenResponseResultsInner {
    return SafeHavenResponseResultsInnerFromJSONTyped(json, false);
}

export function SafeHavenResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeHavenResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'score': json['score'],
        'volatility': json['volatility'],
        'maxDrawdownPct': json['maxDrawdownPct'],
        'crisisReturnPct': json['crisisReturnPct'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function SafeHavenResponseResultsInnerToJSON(json: any): SafeHavenResponseResultsInner {
    return SafeHavenResponseResultsInnerToJSONTyped(json, false);
}

export function SafeHavenResponseResultsInnerToJSONTyped(value?: SafeHavenResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'score': value['score'],
        'volatility': value['volatility'],
        'maxDrawdownPct': value['maxDrawdownPct'],
        'crisisReturnPct': value['crisisReturnPct'],
        'note': value['note'],
    };
}

