/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeHavenResponseResultsInner } from './SafeHavenResponseResultsInner';
import {
    SafeHavenResponseResultsInnerFromJSON,
    SafeHavenResponseResultsInnerFromJSONTyped,
    SafeHavenResponseResultsInnerToJSON,
    SafeHavenResponseResultsInnerToJSONTyped,
} from './SafeHavenResponseResultsInner';
import type { SafeHavenResponseCrisis } from './SafeHavenResponseCrisis';
import {
    SafeHavenResponseCrisisFromJSON,
    SafeHavenResponseCrisisFromJSONTyped,
    SafeHavenResponseCrisisToJSON,
    SafeHavenResponseCrisisToJSONTyped,
} from './SafeHavenResponseCrisis';

/**
 * 
 * @export
 * @interface SafeHavenResponse
 */
export interface SafeHavenResponse {
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponse
     */
    to: string;
    /**
     * 
     * @type {SafeHavenResponseCrisis}
     * @memberof SafeHavenResponse
     */
    crisis: SafeHavenResponseCrisis;
    /**
     * 
     * @type {SafeHavenResponseUniverseEnum}
     * @memberof SafeHavenResponse
     */
    universe?: SafeHavenResponseUniverseEnum;
    /**
     * 
     * @type {Array<SafeHavenResponseResultsInner>}
     * @memberof SafeHavenResponse
     */
    results: Array<SafeHavenResponseResultsInner>;
}


/**
 * @export
 */
export const SafeHavenResponseUniverseEnum = {
    Liquid: 'liquid',
    Majors: 'majors'
} as const;
export type SafeHavenResponseUniverseEnum = typeof SafeHavenResponseUniverseEnum[keyof typeof SafeHavenResponseUniverseEnum];


/**
 * Check if a given object implements the SafeHavenResponse interface.
 */
export function instanceOfSafeHavenResponse(value: object): value is SafeHavenResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('crisis' in value) || value['crisis'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function SafeHavenResponseFromJSON(json: any): SafeHavenResponse {
    return SafeHavenResponseFromJSONTyped(json, false);
}

export function SafeHavenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeHavenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'crisis': SafeHavenResponseCrisisFromJSON(json['crisis']),
        'universe': json['universe'] == null ? undefined : json['universe'],
        'results': ((json['results'] as Array<any>).map(SafeHavenResponseResultsInnerFromJSON)),
    };
}

export function SafeHavenResponseToJSON(json: any): SafeHavenResponse {
    return SafeHavenResponseToJSONTyped(json, false);
}

export function SafeHavenResponseToJSONTyped(value?: SafeHavenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'crisis': SafeHavenResponseCrisisToJSON(value['crisis']),
        'universe': value['universe'],
        'results': ((value['results'] as Array<any>).map(SafeHavenResponseResultsInnerToJSON)),
    };
}

