/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeHavenResponseCrisis
 */
export interface SafeHavenResponseCrisis {
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponseCrisis
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponseCrisis
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof SafeHavenResponseCrisis
     */
    to: string;
}

/**
 * Check if a given object implements the SafeHavenResponseCrisis interface.
 */
export function instanceOfSafeHavenResponseCrisis(value: object): value is SafeHavenResponseCrisis {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function SafeHavenResponseCrisisFromJSON(json: any): SafeHavenResponseCrisis {
    return SafeHavenResponseCrisisFromJSONTyped(json, false);
}

export function SafeHavenResponseCrisisFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeHavenResponseCrisis {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'from': json['from'],
        'to': json['to'],
    };
}

export function SafeHavenResponseCrisisToJSON(json: any): SafeHavenResponseCrisis {
    return SafeHavenResponseCrisisToJSONTyped(json, false);
}

export function SafeHavenResponseCrisisToJSONTyped(value?: SafeHavenResponseCrisis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'from': value['from'],
        'to': value['to'],
    };
}

