/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VolatilityResponseResultsInner
 */
export interface VolatilityResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof VolatilityResponseResultsInner
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof VolatilityResponseResultsInner
     */
    volatility: number | null;
    /**
     * 
     * @type {number}
     * @memberof VolatilityResponseResultsInner
     */
    observations: number;
    /**
     * 
     * @type {string}
     * @memberof VolatilityResponseResultsInner
     */
    note?: string;
}

/**
 * Check if a given object implements the VolatilityResponseResultsInner interface.
 */
export function instanceOfVolatilityResponseResultsInner(value: object): value is VolatilityResponseResultsInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('volatility' in value) || value['volatility'] === undefined) return false;
    if (!('observations' in value) || value['observations'] === undefined) return false;
    return true;
}

export function VolatilityResponseResultsInnerFromJSON(json: any): VolatilityResponseResultsInner {
    return VolatilityResponseResultsInnerFromJSONTyped(json, false);
}

export function VolatilityResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolatilityResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'volatility': json['volatility'],
        'observations': json['observations'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function VolatilityResponseResultsInnerToJSON(json: any): VolatilityResponseResultsInner {
    return VolatilityResponseResultsInnerToJSONTyped(json, false);
}

export function VolatilityResponseResultsInnerToJSONTyped(value?: VolatilityResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'volatility': value['volatility'],
        'observations': value['observations'],
        'note': value['note'],
    };
}

