/* tslint:disable */
/* eslint-disable */
/**
 * CurrencyCore API
 * Edge-native currency exchange, PPP, and FX analytics API. Authenticate with your API key as `Authorization: Bearer <key>`.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VolatilityResponseResultsInner } from './VolatilityResponseResultsInner';
import {
    VolatilityResponseResultsInnerFromJSON,
    VolatilityResponseResultsInnerFromJSONTyped,
    VolatilityResponseResultsInnerToJSON,
    VolatilityResponseResultsInnerToJSONTyped,
} from './VolatilityResponseResultsInner';

/**
 * 
 * @export
 * @interface VolatilityResponse
 */
export interface VolatilityResponse {
    /**
     * 
     * @type {string}
     * @memberof VolatilityResponse
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof VolatilityResponse
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof VolatilityResponse
     */
    to: string;
    /**
     * 
     * @type {VolatilityResponseModeEnum}
     * @memberof VolatilityResponse
     */
    mode: VolatilityResponseModeEnum;
    /**
     * 
     * @type {VolatilityResponseSortEnum}
     * @memberof VolatilityResponse
     */
    sort?: VolatilityResponseSortEnum;
    /**
     * 
     * @type {VolatilityResponseUniverseEnum}
     * @memberof VolatilityResponse
     */
    universe?: VolatilityResponseUniverseEnum;
    /**
     * 
     * @type {VolatilityResponseBasisEnum}
     * @memberof VolatilityResponse
     */
    basis: VolatilityResponseBasisEnum;
    /**
     * 
     * @type {Array<VolatilityResponseResultsInner>}
     * @memberof VolatilityResponse
     */
    results: Array<VolatilityResponseResultsInner>;
}


/**
 * @export
 */
export const VolatilityResponseModeEnum = {
    Compare: 'compare',
    Ranking: 'ranking'
} as const;
export type VolatilityResponseModeEnum = typeof VolatilityResponseModeEnum[keyof typeof VolatilityResponseModeEnum];

/**
 * @export
 */
export const VolatilityResponseSortEnum = {
    Stable: 'stable',
    Volatile: 'volatile'
} as const;
export type VolatilityResponseSortEnum = typeof VolatilityResponseSortEnum[keyof typeof VolatilityResponseSortEnum];

/**
 * @export
 */
export const VolatilityResponseUniverseEnum = {
    Liquid: 'liquid',
    Majors: 'majors'
} as const;
export type VolatilityResponseUniverseEnum = typeof VolatilityResponseUniverseEnum[keyof typeof VolatilityResponseUniverseEnum];

/**
 * @export
 */
export const VolatilityResponseBasisEnum = {
    AnnualizedDaily: 'annualized-daily'
} as const;
export type VolatilityResponseBasisEnum = typeof VolatilityResponseBasisEnum[keyof typeof VolatilityResponseBasisEnum];


/**
 * Check if a given object implements the VolatilityResponse interface.
 */
export function instanceOfVolatilityResponse(value: object): value is VolatilityResponse {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('basis' in value) || value['basis'] === undefined) return false;
    if (value['basis'] !== 'annualized-daily') return false;
    
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function VolatilityResponseFromJSON(json: any): VolatilityResponse {
    return VolatilityResponseFromJSONTyped(json, false);
}

export function VolatilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolatilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'from': json['from'],
        'to': json['to'],
        'mode': json['mode'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'universe': json['universe'] == null ? undefined : json['universe'],
        'basis': json['basis'],
        'results': ((json['results'] as Array<any>).map(VolatilityResponseResultsInnerFromJSON)),
    };
}

export function VolatilityResponseToJSON(json: any): VolatilityResponse {
    return VolatilityResponseToJSONTyped(json, false);
}

export function VolatilityResponseToJSONTyped(value?: VolatilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'from': value['from'],
        'to': value['to'],
        'mode': value['mode'],
        'sort': value['sort'],
        'universe': value['universe'],
        'basis': value['basis'],
        'results': ((value['results'] as Array<any>).map(VolatilityResponseResultsInnerToJSON)),
    };
}

